#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Sep 27, 2022 10:04:54 AM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import app_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black'
_tabfg2 = 'black'
_tabbg1 = 'grey75'
_tabbg2 = 'grey89'
_bgmode = 'light'

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+552+313")
        top.minsize(120, 1)
        top.maxsize(1698, 984)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(relief="raised")
        top.configure(background="#161a1e")
        top.configure(highlightcolor="#ffffff")

        self.top = top

        self.Button_temp_up = tk.Button(self.top)
        self.Button_temp_up.place(relx=0.75, rely=0.156, height=84, width=107)
        self.Button_temp_up.configure(activebackground="beige")
        self.Button_temp_up.configure(activeforeground="#ffffff")
        self.Button_temp_up.configure(background="#2c3945")
        self.Button_temp_up.configure(borderwidth="1")
        self.Button_temp_up.configure(compound='left')
        self.Button_temp_up.configure(disabledforeground="#ffffff")
        self.Button_temp_up.configure(font="-family {Segoe UI} -size 9")
        self.Button_temp_up.configure(foreground="#d1d9e0")
        self.Button_temp_up.configure(highlightbackground="#6d4b03")
        self.Button_temp_up.configure(highlightcolor="#fcb6c9")
        self.Button_temp_up.configure(pady="0")
        self.Button_temp_up.configure(relief="solid")
        self.Button_temp_up.configure(text='''Button''')

def start_up():
    app_support.main()

if __name__ == '__main__':
    app_support.main()




